[package]
name = "agnaji"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/CodingRays/Agnaji"

[dependencies]
ash = "0.37.1"
log = "0.4.17"
rand = "0.8.5"
static_assertions = "1.1.0"

[dev-dependencies]
pretty_env_logger = "0.4.0"